// <auto-generated />
using System;
using MedicalDiagnosis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalDiagnosis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403110211_FixUserSession")]
    partial class FixUserSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.Doctor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("license_number");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specialization");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("UserId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("[license_number] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            LicenseNumber = "BS-HN-001",
                            Specialization = "Chẩn đoán hình ảnh",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            UserId = 3,
                            LicenseNumber = "BS-HCM-002",
                            Specialization = "X-quang phổi",
                            YearsOfExperience = 7
                        });
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.Patient", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.HasKey("UserId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            UserId = 4,
                            Address = "Demo address 1",
                            Gender = "Male",
                            Phone = "0000000001"
                        },
                        new
                        {
                            UserId = 5,
                            Address = "Demo address 2",
                            Gender = "Female",
                            Phone = "0000000002"
                        });
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "doctor"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "patient"
                        });
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@example.com",
                            FailedAttempts = 0,
                            FullName = "Quản Trị Viên",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$AAAAAAAAAAAAAAAAAAAAAAO8GmFD3MfLkBMW6E.8eRNPFSFl6YFHS",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor1@example.com",
                            FailedAttempts = 0,
                            FullName = "BS. Nguyễn Văn An",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$BBBBBBBBBBBBBBBBBBBBBBO3HnGE4NmGlCNb7F9fSGTGHl7ZFHS",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "bs_nguyen"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor2@example.com",
                            FailedAttempts = 0,
                            FullName = "BS. Trần Thị Bình",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$BBBBBBBBBBBBBBBBBBBBBBO3HnGE4NmGlCNb7F9fSGTGHl7ZFHS",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "bs_tran"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient1@example.com",
                            FailedAttempts = 0,
                            FullName = "Hoàng Minh Tuấn",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$CCCCCCCCCCCCCCCCCCCCCCo3HnGE4NmGlCNb7F9fSGTGHl7ZFHS",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "bn_hoang"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient2@example.com",
                            FailedAttempts = 0,
                            FullName = "Lê Thị Thu",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$CCCCCCCCCCCCCCCCCCCCCCo3HnGE4NmGlCNb7F9fSGTGHl7ZFHS",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "bn_le"
                        });
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("User_Sessions");
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.Doctor", b =>
                {
                    b.HasOne("MedicalDiagnosis.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("MedicalDiagnosis.Core.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.Patient", b =>
                {
                    b.HasOne("MedicalDiagnosis.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("MedicalDiagnosis.Core.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.User", b =>
                {
                    b.HasOne("MedicalDiagnosis.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MedicalDiagnosis.Core.Entities.UserSession", b =>
                {
                    b.HasOne("MedicalDiagnosis.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
